### ISSUE TITLE
My local music not showing

### ISSUE THREAD

**Issue by bee8875** [you-apps/VibeYou#110]
### Steps to reproduce

My local music not showing in app
And online music is not work properly 

### Expected behavior

Showing my local music 

### Actual behavior

My local music not showing 

### Vibe You version

4.0

### Android version

Android 14

### Other details

Local music not showing 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You have to grant the requested permissions and then restart the app.

**Comment by bee8875** [comment]
These are basic things I know about it.
I do everything but music files not showing,
I am using Realme P1 5G device.
