### ISSUE TITLE
Login to the Piped account

### ISSUE THREAD

**Issue by siggi1984** [you-apps/VibeYou#2]
Would it be possible to add a login to the Piped account to access his playlists.
Would also be a great backup option for songs and playlists.

**Comment by SuhasDissa** [comment]
Hey there!

I wanted to let you know that adding the ability to login to Piped account is taking a bit longer than expected. I'm running into some trouble with the Piped servers, which are sending a 403 error when I try to login. I haven't been able to find any documentation on their API authentication, so I'm still trying to figure out what's going on.

In the meantime, I got inspired by your request and added playlist, artist, and album search support to the app. The next release will include these features.

I'll keep you updated on my progress, and I'll let you know as soon as I have more information about the login feature.

**Comment by siggi1984** [comment]
ok all good bro
I was probably too hasty. was very curious.

Thank you for your work and I look forward to the next versions

**Comment by siggi1984** [comment]
hey bro, if you don't mind i would like to translate your app into german language. tell me which file i need to translate?

**Comment by SuhasDissa** [comment]
I will open a Crowdin project.

**Comment by siggi1984** [comment]
when I use the piped instance kavin.rocks the app doesn't work for me.
![Uploading Screenshot_20230812-131939_MellowMusic.jpg…]()

**Comment by siggi1984** [comment]
when I use the piped instance kavin.rocks the app doesn't work for me. 
![Screenshot_20230812-131939_MellowMusic](https://github.com/SuhasDissa/MellowMusic/assets/103368536/501e8e6a-861c-42d4-8a3c-53708f4860ef)

**Comment by SuhasDissa** [comment]
Use whatever.social

**Comment by SuhasDissa** [comment]
> hey bro, if you don't mind i would like to translate your app into german language. tell me which file i need to translate?

https://crowdin.com/project/mellowmusic

Use this link to translate

**Comment by siggi1984** [comment]
okay have translated it, do I need to do anything else there

**Comment by SuhasDissa** [comment]
No, Crowdin will make a PR sometime soon

**Comment by SuhasDissa** [comment]
BTW translate the text not the key

![image](https://github.com/SuhasDissa/MellowMusic/assets/64766434/fadc4a25-c4d1-4a75-b25e-3f440b5c3872)

**Comment by siggi1984** [comment]
> BTW translate the text not the key
> 
> ![image](https://user-images.githubusercontent.com/64766434/260252307-fadc4a25-c4d1-4a75-b25e-3f440b5c3872.png)

oy my mistake, I will pay attention next time.

**Comment by siggi1984** [comment]
because they are already working on this function, I close this one. please give them a brief notice when the function is finished.
