### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [you-apps/VibeYou#74]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5538547491#L2400

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/1b69c04387e0d0326488491a3f2b06cb1b4d1360

Will diff locally, brb

**Comment by licaon-kter** [comment]
@Bnyro same here? ref: https://github.com/you-apps/ClockYou/issues/208#issuecomment-1812920938

**Comment by Bnyro** [comment]
I rebuilt the app but the diff is still present :///
```
❯ zipcmp app-release.apk gh-release.apk
--- app-release.apk
+++ gh-release.apk
- file 'assets/dexopt/baseline.prof', size 5219, crc 2fb6dc7b
+ file 'assets/dexopt/baseline.prof', size 5219, crc 5a420b39
- file 'classes.dex', size 4471120, crc a7e89972
+ file 'classes.dex', size 4471276, crc 92a04fca
```

**Comment by SuhasDissa** [comment]
Why don't we just upload this : https://gitlab.com/fdroid/fdroiddata/-/jobs/5538547491/artifacts/file/tmp/app.suhasdissa.vibeyou_2.apk as the github release

**Comment by SuhasDissa** [comment]
I was able to successfully build the apk
[VibeYou-signed.zip](https://github.com/you-apps/VibeYou/files/13377274/VibeYou-signed.zip)

**Comment by licaon-kter** [comment]
Confirmedrepro indeed, you're gonna replace that APK in the tagged release or ?

**Comment by SuhasDissa** [comment]
> Confirmed repro indeed 🎉 , you're gonna replace that APK in the tagged release or ?

@Bnyro should I replace it?

**Comment by SuhasDissa** [comment]
> Confirmed repro indeed 🎉 , you're gonna replace that APK in the tagged release or ?

I just updated the release

**Comment by licaon-kter** [comment]
@SuhasDissa pls rename apk to `app-release.apk` as the older ones are in https://github.com/you-apps/VibeYou/releases/tag/v2.0

**Comment by SuhasDissa** [comment]
> @SuhasDissa pls rename apk to `app-release.apk` as the older ones are in https://github.com/you-apps/VibeYou/releases/tag/v2.0

Renamed it.
