### ISSUE TITLE
Pulling the left side panel more comfortably

### ISSUE THREAD

**Issue by serrq** [you-apps/VibeYou#78]
In Vibe the left panel is openable just from upper positions.
In other apps I can pull the side panel from any position sidely. Even from bottom.

Might you improve this aspect?

![1000098587](https://github.com/you-apps/VibeYou/assets/113377431/e5dbaff4-7874-4bef-b0c8-5c60c4d0bf74)

**Comment by SuhasDissa** [comment]
We had to disable that functionality as it was interfering with the swipe gesture that we use to switch tabs.
