### ISSUE TITLE
Custom Instances

### ISSUE THREAD

**Issue by kubo6472** [you-apps/VibeYou#93]
### Steps to reproduce

1. Settings
2. Network settings
3. Change server

### Expected behavior

Next to change server:
Custom instance (@Bnyro has this in Libre Tube: https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt)
Authentication instance (auth proposed already in #2)

### Actual behavior

Only a selection of instances

### Vibe You version

2.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/you-apps/VibeYou/pull/83
