### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by dfbgcnff** [you-apps/VibeYou#95]
### Describe your suggested feature

It would improve the user experience to have the next song in the queue play when the song ends when streaming from piped.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
Please provide a more detailed description.
